"""The part of the Plugin class that catches up state left by an older version.

Everything here runs once, from `_main`, on a device that already has data on
it. A launcher was generated by a version that wrote them differently; a game
was added before per-platform collections existed; an emulator was installed
with launch arguments that have since been corrected. None of that is fixed by
shipping the fix -- the value was written at install time and nothing revisits
it -- so each of these is a pass over what is already there.

Split out because the set only ever grows. Every feature that changes how
something is *written* needs a step here for the devices that already have the
old shape, and there is no point at which that stops being true: they
accumulated to a third of main.py, in the middle of the file, between startup
and the endpoints. Two properties are worth having them together for:

* They share a shape, and it is easy to get wrong. Each one asks whether it has
  already run, does its work, and records that it has -- and the recording is
  unconditional, so a device with nothing to migrate does not decide it is
  behind on every start. `_upgrade_launchers` and `_adopt_menu_combo` both store
  their marker before checking whether the library is empty, for that reason.
* They are all allowed to fail. `_main` catches each one separately and carries
  on, because a migration that raises is a permanent failure otherwise --
  nothing about the state that broke it changes between starts, so one
  unreadable launcher would cost every step after it, forever. The ordering and
  the reasoning behind it stay in `_main`, which is where the sequence is read.

Mixed into `Plugin` rather than called by it, like the other five: these use
`self._run`, `self.rebuild_launchers` and four more members of the composed
class (see plugin_base.py), and nothing here may be instantiated alone.
"""

import decky

import plugin_base

import emu_config
import emu_install
import emu_patch
import emu_firmware
import emulator_catalog
import steam_layouts
import emulators
import installer
import launchers
import store


class Startup(plugin_base.PluginContext):
    """One-time migrations of data already on the device. See the module docstring."""

    async def _adopt_menu_combo(self):
        """Give games added before the menu shortcut existed a way into the menu.

        A default only reaches a game when its launcher is written, and nothing
        rewrites launchers on upgrade -- so an existing library would keep no
        shortcut at all until the user happened to change some other launch
        setting, which looks exactly like the feature not working.
        """
        if "menu_combo" in await self._run(store.stored_keys):
            return

        settings = await self._run(store.get_settings)
        # Stored explicitly so this runs once, whether or not anything is rebuilt
        # below -- and so turning it back off is not undone at the next startup.
        combo = self._menu_combo(settings)
        await self._run(store.set_settings, {"menu_combo": combo})

        if not await self._run(store.get_library):
            return
        decky.logger.info("Adding the %s menu shortcut to existing launchers", combo)
        await self.rebuild_launchers()

    async def _pin_collection_layout(self):
        """Leave an existing library on the collection layout it was filed under.

        `collection_per_platform` defaults on now. Settings are merged from the
        defaults when they are read rather than written at install, so changing
        one changes it for everybody who never opened that toggle -- and this
        one decides where a game is filed. Their next added game would land on a
        per-system shelf while every game already added stayed on the shared
        one: nothing moved, and a library split across two schemes.

        So anyone with games keeps what those games were filed under, written
        down explicitly. Changing it in the panel still migrates the library,
        which is the supported way to move between the two.

        **What that is decided from is the whole of this.** It used to be "the
        library is not empty", on the reasoning that a library older than the
        setting must predate the setting. That is true for exactly one
        population -- people upgrading across the release that added per-platform
        collections -- and false for everyone else, because the key is only ever
        stored by this method or by the toggle in the panel. So a fresh install
        where somebody added a game before their first restart got the layout
        turned off underneath them, and so did every install after a state reset,
        which clears settings.json and leaves the library newer than it. The
        migration produced the exact split it exists to prevent, repeatedly.

        The evidence was already there: every entry records the collection it was
        filed into. Games sitting on per-system shelves *are* the per-platform
        layout in use, whatever the settings file has lost. Only a library filed
        under one shared name -- or filed before that was recorded at all, which
        is the same old install -- pins to the shared layout.

        Either way the answer is written down, so this runs once and stops
        asking.
        """
        if "collection_per_platform" in await self._run(store.stored_keys):
            return
        library = await self._run(store.get_library)
        if not library:
            return

        settings = await self._run(store.get_settings)
        # Under the shared layout every game carries the same name, so anything
        # else that is recorded is a per-system shelf. Compared against a name
        # built here rather than matched by pattern: the template is
        # configurable, and a pattern would have to know all seven formats.
        shared = self._collection_name(dict(settings, collection_per_platform=False), "")
        filed = {(entry or {}).get("collection") or "" for entry in library.values()}
        per_platform = {name for name in filed if name and name != shared}

        if per_platform:
            await self._run(store.set_settings, {"collection_per_platform": True})
            decky.logger.info(
                "Library is already filed per system (%s); keeping that layout",
                ", ".join(sorted(per_platform)[:3]),
            )
            return

        await self._run(store.set_settings, {"collection_per_platform": False})
        decky.logger.info(
            "Existing library: staying on one shared collection until it is changed",
        )

    async def _write_gyro_layout(self):
        """Derive the Steam layout an emulator's motion support depends on.

        Vita3K is the only entry that asks for one, and it asks because the Deck
        powers its gyro down unless the running game's layout binds it. Steam's
        own gyro template binds it to the mouse, which drifts a pointer Vita3K
        reads as the Vita's touchscreen -- so the layout it points at is one
        derived from Valve's, with the gyro sent to a stick instead.

        Every startup rather than at install: Steam updates rewrite its
        templates, and a derived one that stopped matching would quietly hold a
        year-old copy of somebody else's tuning.
        """
        # Asked for through a workaround rather than the entry, since both
        # emulators that want it declare motion as one -- and derived even
        # when a user has motion switched off, because the template is
        # shared and turning it back on should not wait for a restart.
        wanted = [
            entry for entry in emulator_catalog.CATALOG
            if any(
                str((item.get("apply") or {}).get("layout") or "")
                .endswith(steam_layouts.DERIVED)
                for item in emulator_catalog.workarounds_for(entry)
            ) or str(entry.get("layout") or "").endswith(steam_layouts.DERIVED)
        ]
        if not wanted:
            return
        _path, error = await self._run(steam_layouts.ensure)
        if error:
            # Not fatal: without it a Vita game lands on whatever Steam chose,
            # which is the situation this improves rather than depends on.
            decky.logger.warning("Could not write the gyro layout: %s", error)

    async def _upgrade_emulator_recipes(self):
        """Carry a corrected launch recipe to an emulator already installed.

        Launch arguments are written once, when the emulator is installed, so a
        fix to them would otherwise reach nobody who already had it -- and
        PCSX2's needed one, to stop its main window appearing for a second
        before the game and to make quitting the game exit rather than drop back
        to its game list.

        Only touched when the stored arguments are still exactly what the
        catalog last supplied. Anything edited in the emulator editor is the
        user's and is left alone, which is the same rule `emu_config` uses.
        """
        changed = []
        # Read once for the whole pass, and only because something below needs
        # it: this is what `extensions_for` derives a libretro-backed emulator's
        # formats from, and it is a cached file rather than a fetch in the
        # ordinary case.
        extension_map = None

        for emulator in await self._refresh_emulators():
            entry = emulator_catalog.find(emulator.get("id", ""))
            if not entry:
                continue
            recipe = entry.get("recipe", 1)
            # Whether the *launch recipe* moved. Extensions are checked either
            # way, below: they carry their own provenance in
            # `catalog_extensions`, so telling this plugin's last answer from a
            # user's edit does not need a version at all -- and gating them on
            # one meant a format added to the catalog reached nobody who already
            # had the emulator until somebody remembered to bump it. Nobody did:
            # Xenia gained `zar` and `stfs` and went on claiming `iso` and `xex`
            # on the one device it was installed on, so an unpacked XBLA title
            # was offered no emulator at all.
            fresh = emulator.get("catalog_recipe", 1) != recipe
            before = (emulator.get("args"), emulator.get("fullscreen_args"),
                      emulator.get("command"), dict(emulator.get("env") or {}),
                      emulator.get("installed_args"), emulator.get("layout"),
                      emulator.get("splits_args"),
                      list(emulator.get("extensions") or []),
                      list(emulator.get("catalog_extensions") or []),
                      emulator.get("catalog_recipe"),
                      list(emulator.get("workarounds_off") or []))

            # Only for an entry that needs it. A libretro-backed emulator
            # derives its formats from this map; one with no databases derives
            # entirely from MANUAL_EXTENSIONS and must not pay for the read.
            if extension_map is None and entry.get("databases"):
                extension_map = await self._run(installer.database_extensions)

            stored = emulator.get("catalog_args")
            if not fresh:
                pass
            elif stored is not None and emulator.get("args") != stored:
                # Edited here, so the recipe is no longer ours to change. The
                # version is still recorded, or this would ask again forever.
                decky.logger.info(
                    "Leaving %s launch arguments alone; they were edited", emulator["id"]
                )
            else:
                emulator["args"] = entry.get("args") or "{rom}"
                emulator["fullscreen_args"] = entry.get("fullscreen_args") or ""
                changed.append(emulator["id"])

            # Files the package ships where the emulator cannot find them,
            # replaced if they have gone. Here rather than only at install for
            # the reason the extensions below are here: a fault found after
            # somebody already has the emulator reaches nobody otherwise, and
            # this one is not a degraded feature -- without it Supermodel exits
            # before its first frame. Costs a `listdir` per catalog emulator
            # that declares one, which is one of them.
            if entry.get("seed"):
                _seeded, _seed_error = await self._run(
                    emu_install.seed_bundled_files,
                    (entry.get("source") or {}).get("id", ""),
                    entry["seed"],
                )
                if _seed_error:
                    decky.logger.warning(
                        "Could not seed %s: %s", emulator["id"], _seed_error)

            # Taken from the entry whenever the recipe moved, unlike the
            # arguments above: neither is editable in the emulator editor, so
            # neither can be the user's.
            # They are also the two that decide whether the emulator runs at
            # all -- shadPS4's launches the wrong binary without `command` and
            # renders on the CPU without `env` -- so a stale one is not a
            # cosmetic difference.
            # What this install will actually run: the entry with the
            # corrections the user has left on merged in, and the ones they
            # turned off absent. Resolved once here so nothing downstream
            # has to ask which are enabled.
            # Absent is not the same as empty. A record written before this
            # existed has no key at all, and reading that as "nothing is
            # switched off" would hand it every correction including the ones
            # that default to off -- turning motion on, and Steam Input off,
            # for somebody who never asked. Absent means "apply the
            # defaults", and the answer is then written down so it is a
            # recorded choice rather than something re-derived every start.
            if emulator.get("workarounds_off") is None:
                emulator["workarounds_off"] = emulator_catalog.default_disabled(entry)
            effective = emulator_catalog.resolve_workarounds(
                entry, emulator["workarounds_off"])

            if fresh:
                emulator["command"] = entry.get("command", "")
                emulator["installed_args"] = entry.get("installed_args", "")
                emulator["splits_args"] = bool(entry.get("splits_args"))

            # Every start, unlike the recipe fields above, for the reason
            # `layout` is: a workaround the user switched off has to stop
            # applying now rather than at the next recipe bump, and there is
            # no user-edited value here to preserve -- the editor never sends
            # `env`.
            if emulator.get("env") != dict(effective.get("env") or {}):
                emulator["env"] = dict(effective.get("env") or {})
                changed.append(emulator["id"])

            # Refreshed every start, unlike the recipe fields above. It is not
            # editable anywhere, so there is no user value to preserve -- and
            # gating it on the recipe leaves it stranded in two real cases: the
            # version that added it forgot to raise the number, and a plugin
            # downgrade re-saves the record through a `save()` that has never
            # heard of the field and drops it, with the recipe left saying
            # everything is current. Both end as an emulator whose games get no
            # layout and a gyro nobody can switch on.
            emulator["layout"] = effective.get("layout", "")

            # Which files the picker offers this emulator for. Stored at install
            # time and never revisited, so narrowing a system's formats reached
            # nobody who already had the emulator: Vita3K stopped claiming .vpk
            # in the catalog and went on claiming it on every device where it
            # was installed, which is the whole reason a .vpk was still offered
            # a "Run with" it could not honour.
            #
            # Editable in the emulator editor, so the same rule the arguments
            # use applies -- refreshed only while it is still exactly what the
            # catalog last supplied.
            derived = emulator_catalog.extensions_for(entry, extension_map)
            # An empty answer means the map could not be read, and so does a
            # libretro-backed emulator with no map: both are "cannot tell", and
            # writing a shorter list on a guess would stop the emulator matching
            # ROMs it handles. An entry with no databases derives entirely from
            # MANUAL_EXTENSIONS, so for those the map is not needed at all.
            if derived and (extension_map or not entry.get("databases")):
                stored_ext = emulator.get("catalog_extensions")
                if stored_ext is not None and emulator.get("extensions") != stored_ext:
                    decky.logger.info(
                        "Leaving %s file extensions alone; they were edited", emulator["id"]
                    )
                elif emulator.get("extensions") != derived:
                    emulator["extensions"] = derived
                    changed.append(emulator["id"])
                emulator["catalog_extensions"] = derived

            if fresh:
                emulator["catalog_recipe"] = recipe
                emulator["catalog_args"] = entry.get("args") or "{rom}"
                emulator["catalog_fullscreen_args"] = entry.get("fullscreen_args") or ""

            # Saved only when something actually moved. This pass now runs over
            # every catalog emulator on every startup rather than only the ones
            # whose recipe changed, and rewriting nine unchanged records each
            # time is how a settings file gets a reputation for churn.
            after = (emulator.get("args"), emulator.get("fullscreen_args"),
                     emulator.get("command"), dict(emulator.get("env") or {}),
                     emulator.get("installed_args"), emulator.get("layout"),
                     emulator.get("splits_args"),
                     list(emulator.get("extensions") or []),
                     list(emulator.get("catalog_extensions") or []),
                     emulator.get("catalog_recipe"),
                     list(emulator.get("workarounds_off") or []))
            if after != before:
                await self._run(emulators.save, emulator)

        if changed:
            # Every launcher already written bakes in the old argv, so the fix
            # reaches nothing until they are rewritten.
            decky.logger.info("Updated launch recipe for %s", ", ".join(changed))
            await self._refresh_emulators()
            await self.rebuild_launchers()

    async def _upgrade_emulator_setups(self):
        """Re-apply recommended settings an emulator installed earlier has missed.

        Settings are written when an emulator is installed, and an emulator is
        installed once -- so a *correction* to those settings would otherwise
        only ever reach someone who had not installed it yet. The first Azahar
        bindings were wrong, and the only route to the fixed ones was deleting a
        hundred-megabyte AppImage and downloading it again.

        Safe to run unattended because the rule in `emu_config` decides what may
        be touched: anything the user set themselves is left alone, and only
        values still at the emulator's own default or previously written by this
        plugin are rewritten.
        """
        for entry in emulator_catalog.CATALOG:
            if not entry.get("setup"):
                continue
            if not await self._run(emu_config.needs_setup, entry):
                continue

            if entry["source"]["kind"] == "flatpak":
                present = await self._run(
                    emu_install.flatpak_installed, entry["source"]["id"]
                )
            else:
                present = bool(await self._run(emu_install.installed_appimage, entry["id"]))
            if not present:
                continue

            decky.logger.info("Updating recommended settings for %s", entry["id"])
            result = await self._run(emu_config.apply_setup, entry)
            if not result.get("ok"):
                decky.logger.warning(
                    "Could not update %s settings: %s", entry["id"], result.get("error")
                )

    async def _prepare_patched_builds(self):
        """Make the patched build for an install that predates the patcher.

        A patched build is normally derived as the emulator installs, and every
        install from here on has one. An emulator installed before that has an
        AppImage and no record beside it, and would otherwise sit there with a
        switch it can never honour until somebody happened to reinstall.

        Only where nothing has been attempted yet. A record already present is
        an answer -- including "this build would not take it", which is a
        finding to report rather than a question to ask again on every start.
        """
        changed = False
        for entry in emulator_catalog.CATALOG:
            if not emu_patch.patch_specs(entry):
                continue
            if await self._run(emu_patch.read_record, entry["id"]):
                continue
            stock = await self._run(emu_install.installed_appimage, entry["id"])
            if not stock:
                continue
            decky.logger.info("Preparing patched builds for %s", entry["id"])
            await self._run(emu_patch.refresh, entry, stock)
            changed = True

        # Which binary a launcher execs is decided by whether the patched build
        # exists, and this is the other place that changes it. `install_appimage`
        # rebuilds for the same reason; without it here, an install that gains a
        # patched build keeps launching the stock one, and one whose patch is
        # refused keeps naming a file that was never made.
        if changed:
            await self.rebuild_launchers()

    async def _recheck_emulator_setups(self):
        """The same sweep, for the moments between one startup and the next.

        Startup is too rare to be the only time this runs. An emulator that has
        never run has no config, so installing one means writing settings into a
        file created from nothing -- and its first real run regenerates that
        file with its own defaults and throws them away. That is not a rare
        case: it is what happens to *every* emulator installed and then opened
        in the same session.

        It happened to Azahar on a real device, and the log reads as a plugin
        that did everything right: "Configured azahar: 17 written" at install,
        a 2189-byte config holding exactly those keys, and then a 34086-byte one
        written by Azahar minutes later with every binding back to its keyboard
        default. `needs_setup` knew -- the stamp no longer matched -- but
        nothing asked it again until the next startup, and the game in between
        launched with no controls.

        So the paths that run before somebody plays ask too. Cheap by
        construction: `needs_setup` stats a file per entry and stops there, and
        the expensive probes behind it only run for an entry that is actually
        stale.

        Never raises. It is called from `get_status`, which is what the panel
        opens on -- a failure here must degrade to stale settings, not to a
        panel that will not load.
        """
        try:
            await self._upgrade_emulator_setups()
        except Exception:
            decky.logger.exception("Could not re-check emulator settings")
        try:
            await self._prepare_patched_builds()
        except Exception:
            decky.logger.exception("Could not prepare patched builds")

    async def _claim_filed_collections(self):
        """Record the collections an existing library is already filed into.

        The record of which collections are ours is written as games are filed,
        so an install that predates it starts empty -- and every shelf it made
        would be recognised only by the name pattern, which is exactly the thing
        that loses them the moment the naming changes. One pass over the library
        at startup gives those installs the same footing as a new one.

        Cheap to repeat and safe to: `remember_collections` adds only what is
        missing and reports what it added, so this settles to doing nothing.
        """
        library = await self._run(store.get_library)
        if not library:
            return
        added = await self._run(
            store.remember_collections,
            [entry.get("collection", "") for entry in library.values()],
        )
        if added:
            decky.logger.info(
                "Claiming %d collection(s) this library is already filed into: %s",
                len(added), ", ".join(added),
            )

    async def _upgrade_launchers(self):
        """Rewrite launchers when the format they were written in is out of date.

        A launcher is generated once and never revisited, so a fix to how they
        are written reaches only games added afterwards. That is the failure
        `_adopt_menu_combo` was written for, one flag at a time; a version number
        covers the next one too.

        Recorded even when there is nothing to rebuild, so a fresh install does
        not spend its first startup deciding it is behind.
        """
        settings = await self._run(store.get_settings)
        if settings.get("launcher_format") == launchers.FORMAT_VERSION:
            return

        await self._run(store.set_settings, {"launcher_format": launchers.FORMAT_VERSION})
        if not await self._run(store.get_library):
            return

        decky.logger.info(
            "Rewriting launchers for format %d", launchers.FORMAT_VERSION
        )
        await self.rebuild_launchers()

    async def _forget_removed_settings(self):
        """Clear settings that have been taken out of the plugin.

        The one this exists for is the GitHub token, which the update check
        needed while this repository was private. Nothing reads it now, and a
        credential nothing reads is still a credential in a file -- so it is
        deleted rather than left to be ignored. It also has to go: `get_settings`
        merges the stored file over the defaults, so a key that is no longer
        declared is still handed to every reader, the frontend included.
        """
        gone = await self._run(store.forget_removed)
        if gone:
            decky.logger.info("Removed setting(s) no longer used: %s", ", ".join(gone))

    async def _resplit_firmware_records(self):
        """Re-file records written when one requirement accepted several files.

        Ryujinx's keys were one row matching both prod.keys and title.keys, and
        are now a row each -- because a row is the only way to send a file, and
        a row with anything installed offers Delete where Send would be, so
        installing prod.keys first left title.keys no route at all.

        The record is keyed by requirement name, so the rename orphans it. That
        is not cosmetic: `status` reports anything at the destination this
        plugin cannot account for as *foreign*, and the removal dialog warns
        about foreign files -- so without this, a device that installed its keys
        through the plugin would be told its own prod.keys was somebody else's.

        The pairs are listed rather than derived. A rename is only knowable by
        having made it, and a guess at which old name became which new ones is
        the kind of cleverness that quietly re-files the wrong thing.
        """
        renamed = (("ryujinx", "prod.keys and title.keys"),)
        for entry_id, old_name in renamed:
            entry = emulator_catalog.find(entry_id)
            if not entry:
                continue
            moved = await self._run(
                emu_firmware.resplit_record, entry_id, old_name, entry
            )
            if moved:
                decky.logger.info(
                    "Re-filed %s firmware records from %r: %s",
                    entry_id,
                    old_name,
                    ", ".join(
                        "%s -> %s" % (", ".join(names), target)
                        for target, names in sorted(moved.items())
                    ),
                )

    async def _backfill_library(self):
        """Fill in fields that older versions of this plugin never recorded.

        Games added before per-platform collections existed have no `platform`,
        which would make them fall back to the plain collection name instead of
        being grouped by system. The core id and database name were recorded even
        then, so the label can be recovered.
        """
        library = await self._run(store.get_library)
        # Through the settings rather than _platform_label directly: the stored
        # label is what the games list shows, so a backfilled game would otherwise
        # read "Super Nintendo Entertainment System" while every other game on the
        # same shelf read "SNES".
        settings = await self._run(store.get_settings)
        filled = {}
        for entry in library.values():
            if entry.get("platform"):
                continue
            core = self._core_by_id(entry.get("core_id", ""))
            platform = self._entry_platform(settings, core, entry)
            if not platform:
                continue
            entry["platform"] = platform
            filled[entry["app_id"]] = entry

        # One write for the whole pass. This runs at every startup, and writing
        # per game rewrote the entire registry once per game backfilled.
        if filled:
            await self._run(store.remember_games, filled)
            decky.logger.info("Backfilled platform for %d existing game(s)", len(filled))
